import type * as tools from "@bgord/tools";
import type * as Auth from "../../auth/value-objects";
import type { SupportedLanguages } from "../../supported-languages";
import type { EmotionIntensityType } from "./emotion-intensity";
import type { EntryIdType } from "./entry-id";
import type { EntryOriginOption } from "./entry-origin-option";
import type { EntryStatusEnum } from "./entry-status";
import type { GenevaWheelEmotion } from "./geneva-wheel-emotion.enum";
import type { GrossEmotionRegulationStrategy } from "./gross-emotion-regulation-strategy.enum";
import type { ReactionDescriptionType } from "./reaction-description";
import type { ReactionEffectivenessType } from "./reaction-effectiveness";
import type { SituationDescriptionType } from "./situation-description";
import type { SituationKindOptions } from "./situation-kind-options";
import type { SituationLocationType } from "./situation-location";

export type EntrySnapshot = {
  revision: tools.RevisionValueType;
  startedAt: tools.TimestampType;
  status: EntryStatusEnum;
  id: EntryIdType;
  situationDescription: SituationDescriptionType;
  situationKind: SituationKindOptions;
  situationLocation: SituationLocationType;
  emotionLabel: GenevaWheelEmotion | null;
  emotionIntensity: EmotionIntensityType | null;
  reactionDescription: ReactionDescriptionType | null;
  reactionType: GrossEmotionRegulationStrategy | null;
  reactionEffectiveness: ReactionEffectivenessType | null;
  language: SupportedLanguages;
  weekIsoId: tools.WeekIsoIdType;
  origin: EntryOriginOption;
  userId: Auth.UserIdType;
};
