export enum UsageCategory {
  EMOTIONS_ALARM_ENTRY = "EMOTIONS_ALARM_ENTRY",
  EMOTIONS_ALARM_INACTIVITY = "EMOTIONS_ALARM_INACTIVITY",
  EMOTIONS_WEEKLY_REVIEW_INSIGHT = "EMOTIONS_WEEKLY_REVIEW_INSIGHT",
}
