name: README
on:
  push:
    branches: [master]
  workflow_dispatch:
concurrency:
  group: ci-${{ github.ref }}
  cancel-in-progress: true
jobs:
  generate:
    runs-on: ubuntu-24.04

    permissions:
      contents: write

    steps:
      - name: Check out repository
        uses: actions/checkout@v4
        with:
          submodules: recursive
          fetch-depth: 0

      - name: Generate a README
        run: bgord-scripts/app-readme-generate.sh

      - name: Print README
        run: cat infra/CHANGELOG.md

      - name: Commit readme.md
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          branch: master
          commit_message: "docs: generate readme"
          file_pattern: readme.md
